package edu.neu.universityeventmanagementsystem.business.ui.admin.users.view;

import edu.neu.universityeventmanagementsystem.business.util.ConstantMessages;
import edu.neu.universityeventmanagementsystem.business.util.ImageTools;
import org.apache.log4j.Logger;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * AddUserView class
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since Apr 18, 2018
 */
@Component
@Lazy
public final class AddUserView extends javax.swing.JDialog {

    private static final Logger log = Logger.getLogger(AddUserView.class);

    public static final int COLLEGE = 0;
    public static final int ENTERPRISE = 1;
    public static final int ORGANIZATION = 2;
    public static final int ROLE = 3;

    public static final int EMAIL_ERROR_LABEL = 0;
    public static final int USERNAME_ERROR_LABEL = 1;
    public static final int PASSWORD_ERROR_LABEL = 2;
    public static final int FIRSTNAME_ERROR = 3;
    public static final int LASTNAME_ERROR = 4;
    public static final int MIDDLENAME_ERROR = 5;
    

    private static final int TITLE_BAR_ICON_SIZE = 64;
    private List<JLabel> errorLabels;

    private static boolean modal = true;

    /**
     * Creates new form NewJDialog on a new JFrame and blocks the user input till this dialogue is closed
     */
    public AddUserView() {
        super(new JFrame(), modal);
        initComponents();
        errorLabels = new ArrayList<>(Arrays.asList(lblInvalidEmail, lblUserNameAvailability, lblPasswordError));
        hideAllErrors();
        setLocationRelativeTo(null);
        setCollegeDetailsVisible(false);
        setEnterpriseDetailsVisible(false);
        setOrganizationDetailsVisible(false);
    }

    public void hideAllErrors() {
        errorLabels.forEach(label -> label.setVisible(false));
    }

    public void showError(int choice) {
        try {
            errorLabels.get(choice).setVisible(true);
        } catch (IndexOutOfBoundsException | NullPointerException ex) {
            log.error("Invalid choice", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel contentsPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtFieldFirstName = new javax.swing.JTextField();
        txtFieldMiddleName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtFieldLastName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        txtFieldEmail = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        txtFieldUsername = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();
        pwdFieldConfirm = new javax.swing.JPasswordField();
        lblUserNameAvailability = new javax.swing.JLabel();
        lblInvalidEmail = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        comboBoxRole = new javax.swing.JComboBox<>();
        btnCreateUser = new javax.swing.JButton();
        comboBoxCollege = new javax.swing.JComboBox<>();
        comboBoxEnterprise = new javax.swing.JComboBox<>();
        lblCollege = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        comboBoxOrganization = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConstantMessages.Titles.ADD_USER_TITLE);
        setIconImage(ImageTools.loadImage("add_user_icon_64px.png", TITLE_BAR_ICON_SIZE, TITLE_BAR_ICON_SIZE, true));
        setPreferredSize(new java.awt.Dimension(840, 709));
        setResizable(false);

        contentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentsPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Middle Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Confirm Password");

        lblUserNameAvailability.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserNameAvailability.setForeground(new java.awt.Color(255, 0, 51));
        lblUserNameAvailability.setText("Invalid username.");

        lblInvalidEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInvalidEmail.setForeground(new java.awt.Color(255, 0, 51));
        lblInvalidEmail.setText("Invalid email address.");

        lblPasswordError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 0, 51));
        lblPasswordError.setText("Password do not match.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Account Role");

        btnCreateUser.setBackground(new java.awt.Color(0, 102, 102));
        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUser.setText("Create User");
        btnCreateUser.setBorder(null);
        btnCreateUser.setBorderPainted(false);
        btnCreateUser.setContentAreaFilled(false);
        btnCreateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateUser.setFocusPainted(false);
        btnCreateUser.setOpaque(true);

        lblCollege.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCollege.setText("College");

        lblEnterprise.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEnterprise.setText("Enterprise");

        lblOrganization.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOrganization.setText("Organization");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvalidEmail))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblUserNameAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pwdFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblPasswordError))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(lblCollege, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterprise, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblOrganization)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInvalidEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserNameAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordError))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCollege))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrganization))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEnterprise)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_user_icon_64px.png"))); // NOI18N
        jLabel1.setText("Add New User");

        javax.swing.GroupLayout contentsPanelLayout = new javax.swing.GroupLayout(contentsPanel);
        contentsPanel.setLayout(contentsPanelLayout);
        contentsPanelLayout.setHorizontalGroup(
            contentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        contentsPanelLayout.setVerticalGroup(
            contentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getFirstName() {
        return txtFieldFirstName.getText();
    }

    public String getMiddleName() {
        return txtFieldMiddleName.getText();
    }

    public String getLastName() {
        return txtFieldLastName.getText();
    }

    public String getUserName() {
        return txtFieldUsername.getText();
    }

    public String getEmail() {
        return txtFieldEmail.getText();
    }

    public String getPassword() {
        return String.valueOf(pwdField.getPassword());
    }

    public String getConfirmPassword() {
        return String.valueOf(pwdFieldConfirm.getPassword());
    }

    public String getRole() {
        return String.valueOf(comboBoxRole.getSelectedItem());
    }

    public void setEmail(String email) {
        txtFieldEmail.setText(email);
    }

    public void setRole(String role) {
        comboBoxRole.setSelectedItem(role);
    }

    public javax.swing.JButton getCreateButton() {
        return btnCreateUser;
    }

    public void populateRoles(List<String> roles) {
        comboBoxRole.setModel(new DefaultComboBoxModel<>(roles.toArray(new String[0])));
    }

    public void populateColleges(List<String> colleges) {
        comboBoxCollege.setModel(new DefaultComboBoxModel<>(colleges.toArray(new String[0])));
    }

    public void populateEnterprise(List<String> enterprises) {
        comboBoxEnterprise.setModel(new DefaultComboBoxModel<>(enterprises.toArray(new String[0])));
    }

    public void populateOrganization(List<String> organizations) {
        comboBoxOrganization.setModel(new DefaultComboBoxModel<>(organizations.toArray(new String[0])));
    }

    public void setCollegeDetailsVisible(boolean isVisible) {
        lblCollege.setVisible(isVisible);
        comboBoxCollege.setVisible(isVisible);
    }

    public void setEnterpriseDetailsVisible(boolean isVisible) {
        lblEnterprise.setVisible(isVisible);
        comboBoxEnterprise.setVisible(isVisible);
    }

    public void setOrganizationDetailsVisible(boolean isVisible) {
        lblOrganization.setVisible(isVisible);
        comboBoxOrganization.setVisible(isVisible);
    }

    public JComboBox<String> getComboBox(int which) {
        if (which == COLLEGE) return comboBoxCollege;
        else if (which == ENTERPRISE) return comboBoxEnterprise;
        else if (which == ORGANIZATION) return comboBoxOrganization;
        else return comboBoxRole;
    }

    public String getComboBoxValue(int which) {
        if (which == COLLEGE) return (String) comboBoxCollege.getSelectedItem();
        else if (which == ENTERPRISE) return (String) comboBoxEnterprise.getSelectedItem();
        else if (which == ORGANIZATION) return (String) comboBoxOrganization.getSelectedItem();
        else return (String) comboBoxRole.getSelectedItem();
    }

    public void reset() {
        getContentPane().removeAll();
        initComponents();
        errorLabels = new ArrayList<>(Arrays.asList(lblInvalidEmail, lblUserNameAvailability, lblPasswordError));
        hideAllErrors();
        setLocationRelativeTo(null);
        setCollegeDetailsVisible(false);
        setEnterpriseDetailsVisible(false);
        setOrganizationDetailsVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> comboBoxCollege;
    private javax.swing.JComboBox<String> comboBoxEnterprise;
    private javax.swing.JComboBox<String> comboBoxOrganization;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JLabel lblCollege;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblInvalidEmail;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblUserNameAvailability;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JPasswordField pwdFieldConfirm;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldFirstName;
    private javax.swing.JTextField txtFieldLastName;
    private javax.swing.JTextField txtFieldMiddleName;
    private javax.swing.JTextField txtFieldUsername;
    // End of variables declaration//GEN-END:variables
}
