/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.neu.universityeventmanagementsystem.business.ui.admin.users.view;

import edu.neu.universityeventmanagementsystem.business.entity.UsersEntity;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * UsersView class
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since Apr 15, 2018
 */
@Component
@Lazy
public final class UsersView extends javax.swing.JPanel {

    private final static Color ACTIVE_BACKGROUND = new Color(255, 255, 255);
    private final static Color INACTIVE_BACKGROUND = new Color(240, 240, 240);

    private final static Color ACTIVE_FOREGROUND = new Color(0, 0, 0);
    private final static Color INACTIVE_FOREGROUND = new Color(0, 102, 102);

    /**
     * Creates new form UsersView
     */
    public UsersView() {
        initComponents();
    }

    public List<javax.swing.JButton> getPanelButtons() {
        return new ArrayList<>(Arrays.asList(btnAdmins, btnFaculties, btnStudents, btnSponsors, btnGuests));
    }

    public javax.swing.JButton getAddUserButton() {
        return btnAddUser;
    }

    public void populateTable(List<UsersEntity> users) {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (UsersEntity u : users) {
            row[0] = u.getFirstName();
            row[1] = u.getLastName();
            row[2] = u.getEmail();
            row[3] = u.getUserName();
            row[4] = u.getRolesByIdRole().getName();
            model.addRow(row);
        }
    }

    public void setActiveButton(javax.swing.JButton activeButton) {
        getPanelButtons().forEach(button -> {
            button.setBackground(INACTIVE_BACKGROUND);
            button.setForeground(INACTIVE_FOREGROUND);
        });
        activeButton.setBackground(ACTIVE_BACKGROUND);
        activeButton.setForeground(ACTIVE_FOREGROUND);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        btnAdmins = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnFaculties = new javax.swing.JButton();
        btnGuests = new javax.swing.JButton();
        btnSponsors = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        txtFieldSearch = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1116, 700));

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAdmins.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmins.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdmins.setText("Admins");
        btnAdmins.setBorder(null);
        btnAdmins.setBorderPainted(false);
        btnAdmins.setContentAreaFilled(false);
        btnAdmins.setFocusPainted(false);
        btnAdmins.setOpaque(true);

        btnStudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(0, 102, 102));
        btnStudents.setText("Students");
        btnStudents.setBorder(null);
        btnStudents.setBorderPainted(false);
        btnStudents.setContentAreaFilled(false);
        btnStudents.setFocusPainted(false);
        btnStudents.setOpaque(true);

        btnFaculties.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFaculties.setForeground(new java.awt.Color(0, 102, 102));
        btnFaculties.setText("Faculties");
        btnFaculties.setBorder(null);
        btnFaculties.setBorderPainted(false);
        btnFaculties.setContentAreaFilled(false);
        btnFaculties.setFocusPainted(false);
        btnFaculties.setOpaque(true);

        btnGuests.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuests.setForeground(new java.awt.Color(0, 102, 102));
        btnGuests.setText("Guests");
        btnGuests.setBorder(null);
        btnGuests.setBorderPainted(false);
        btnGuests.setContentAreaFilled(false);
        btnGuests.setFocusPainted(false);
        btnGuests.setOpaque(true);

        btnSponsors.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSponsors.setForeground(new java.awt.Color(0, 102, 102));
        btnSponsors.setText("Sponsors");
        btnSponsors.setBorder(null);
        btnSponsors.setBorderPainted(false);
        btnSponsors.setContentAreaFilled(false);
        btnSponsors.setFocusPainted(false);
        btnSponsors.setOpaque(true);

        btnAddUser.setBackground(new java.awt.Color(0, 102, 102));
        btnAddUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("Add User");
        btnAddUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.setFocusPainted(false);
        btnAddUser.setMaximumSize(new java.awt.Dimension(360, 40));
        btnAddUser.setOpaque(true);
        btnAddUser.setPreferredSize(new java.awt.Dimension(360, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFaculties, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSponsors, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnFaculties, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSponsors, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
        );

        txtFieldSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearchUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchUser.setText("Search");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Find User");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "First Name", "Last Name", "E - Mail", "Username", "Role"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFieldSearch)
                                        .addComponent(btnSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnFaculties;
    private javax.swing.JButton btnGuests;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnSponsors;
    private javax.swing.JButton btnStudents;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtFieldSearch;
    // End of variables declaration//GEN-END:variables

}
