package edu.neu.universityeventmanagementsystem.business.ui.main.view;

import edu.neu.universityeventmanagementsystem.business.util.ConstantMessages;
import edu.neu.universityeventmanagementsystem.business.util.ImageTools;
import edu.neu.universityeventmanagementsystem.business.util.LookAndFeelUtils;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import javax.swing.*;

/**
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @since Apr 10, 2018
 * @version 1.0
 */
@Component
@Lazy
public final class MainFrameView extends javax.swing.JFrame {

    private static final int TITLE_BAR_ICON_SIZE = 64;

    /** Creates new form MainFrame */
    public MainFrameView() {
        initComponents();
        LookAndFeelUtils.setSystemLookAndFeel();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(ConstantMessages.Titles.APPLICATION_TITLE);
        setIconImage(ImageTools.loadImage("application_icon_64px.png", TITLE_BAR_ICON_SIZE, TITLE_BAR_ICON_SIZE, true));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addToPanel(java.awt.Component c) {
        mainPanel.add("NewPanel", c);
        java.awt.CardLayout layout = (java.awt.CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }

    public void removeFromPanel(java.awt.Component c) {
        mainPanel.remove(c);
        java.awt.CardLayout layout = (java.awt.CardLayout) mainPanel.getLayout();
        layout.previous(mainPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
