package edu.neu.universityeventmanagementsystem.business.ui.users.events.view;

import edu.neu.universityeventmanagementsystem.business.entity.EventsEntity;
import edu.neu.universityeventmanagementsystem.business.util.ConstantValues;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import javax.swing.*;
import org.springframework.context.annotation.Scope;

/**
 * EventRequestView class
 *
 * @author  Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since   Apr 25, 2018
 */
@Component
@Lazy
@Scope(value = "prototype")
public class EventRequestView extends javax.swing.JPanel {

    public static final int EVENT_CONFIRMED = 0;
    public static final int EVENT_CONFIRMATION_PENDING = 1;

    private EventsEntity event;

    /** Creates new form EventRequestView */
    public EventRequestView() {
        this(null, -1);
    }

    public EventRequestView(EventsEntity event, int eventStatus) {
        if (event == null) return;
        initComponents();

        if (eventStatus == 0) {
            btnDeleteEvent.setEnabled(false);
            btnEditEvent.setVisible(false);
        }

        if (event.getEventStatusByStatus().getStatusMessage().equals(ConstantValues.EventStatus.CANCELLED)) {
            btnCancelEvent.setText("Cancelled");
            btnCancelEvent.setEnabled(false);
            btnEditEvent.setVisible(false);
        }
    }

    public JButton getBtnCancelEvent() {
        return btnCancelEvent;
    }

    public JButton getBtnDeleteEvent() {
        return btnDeleteEvent;
    }

    public JButton getBtnEditEvent() {
        return btnEditEvent;
    }

    public void setEventView(java.awt.Component view) {
        eventPanel.removeAll();
        eventPanel.add(view);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventPanel = new javax.swing.JPanel();
        btnCancelEvent = new javax.swing.JButton();
        btnDeleteEvent = new javax.swing.JButton();
        btnEditEvent = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 100));

        eventPanel.setBackground(new java.awt.Color(255, 255, 255));
        eventPanel.setPreferredSize(new java.awt.Dimension(480, 100));

        javax.swing.GroupLayout eventPanelLayout = new javax.swing.GroupLayout(eventPanel);
        eventPanel.setLayout(eventPanelLayout);
        eventPanelLayout.setHorizontalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        eventPanelLayout.setVerticalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnCancelEvent.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelEvent.setText("Cancel Event");
        btnCancelEvent.setContentAreaFilled(false);
        btnCancelEvent.setFocusPainted(false);
        btnCancelEvent.setOpaque(true);

        btnDeleteEvent.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEvent.setText("Delete Event");
        btnDeleteEvent.setContentAreaFilled(false);
        btnDeleteEvent.setFocusPainted(false);
        btnDeleteEvent.setOpaque(true);

        btnEditEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_icon_48px.png"))); // NOI18N
        btnEditEvent.setContentAreaFilled(false);
        btnEditEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditEvent.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(eventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnEditEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(eventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnEditEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEvent;
    private javax.swing.JButton btnDeleteEvent;
    private javax.swing.JButton btnEditEvent;
    private javax.swing.JPanel eventPanel;
    // End of variables declaration//GEN-END:variables

}
