/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.neu.universityeventmanagementsystem.business.ui.admin.infrastructure.view;

import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * InfrastructureView class
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since Apr 13, 2018
 */
@Component
@Lazy
public final class InfrastructureView extends javax.swing.JPanel {

    public final static int MAIN_LIST_INDEX = 0;
    public final static int SUB_LIST_INDEX = 1;
    public final static String MAIN_LIST_IDENTIFIER = "mainlist";
    public final static String SUB_LIST_IDENTIFIER = "sublist";
    private final static Color ACTIVE = new Color(6, 136, 136);
    private final static Color INACTIVE = new Color(5, 119, 119);

    private final static String ENTERPRISE_TITLE_TEMPLATE = "Manage your %s here.";

    /**
     * Creates new form InfrastructureView
     */
    public InfrastructureView() {
        initComponents();
        setListModels();
    }

    public void populateLists(List<String> values, int index) {
        DefaultListModel<String> model;
        switch (index) {
            case 0:
                model = (DefaultListModel<String>) listMain.getModel();
                model.clear();
                values.forEach(model::addElement);
                break;
            default:
                model = (DefaultListModel<String>) listSubMain.getModel();
                model.clear();
                values.forEach(model::addElement);
        }
    }

    public javax.swing.JList getListComponent(int index) {
        if (index == 0) {
            return listMain;
        } else {
            return listSubMain;
        }
    }

    public void clearList(int index) {
        if (index == 0) {
            listMain.setModel(new DefaultListModel<>());
        } else {
            listSubMain.setModel(new DefaultListModel<>());
        }
    }

    public List<javax.swing.JButton> getPanelButtons() {
        return new ArrayList<>(Arrays.asList(btnPrograms, btnAdministration, btnCouncils));
    }

    public List<javax.swing.JButton> getAddButtons() {
        return new ArrayList<>(Arrays.asList(btnAddMainList, btnAddSubList));
    }

    public List<javax.swing.JButton> getRemoveButtons() {
        return new ArrayList<>(Arrays.asList(btnRemoveMainList, btnRemoveSubList));
    }

    public void setActiveButton(javax.swing.JButton activeButton) {
        getPanelButtons().forEach(button -> {
            button.setBackground(INACTIVE);
        });
        activeButton.setBackground(ACTIVE);
    }

    private void setListModels() {
        listMain.setModel(new DefaultListModel<>());
        listSubMain.setModel(new DefaultListModel<>());
    }

    public void hideAddDeleteCollegesControl() {
        btnAddMainList.setVisible(false);
        btnRemoveMainList.setVisible(false);
    }

    public void setEnterpriseLabel(String enterprise) {
        lblEnterpriseTitle.setVisible(true);
        lblEnterpriseTitle.setText(String.format(ENTERPRISE_TITLE_TEMPLATE, enterprise));
    }
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        listMain = new javax.swing.JList<>();
        btnAddMainList = new javax.swing.JButton();
        btnRemoveMainList = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        btnPrograms = new javax.swing.JButton();
        btnAdministration = new javax.swing.JButton();
        btnCouncils = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        listSubMain = new javax.swing.JList<>();
        btnRemoveSubList = new javax.swing.JButton();
        btnAddSubList = new javax.swing.JButton();
        lblEnterpriseTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1066, 700));
        setPreferredSize(new java.awt.Dimension(1116, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(315, 618));

        jScrollPane1.setViewportView(listMain);

        btnAddMainList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus_icon_14px.png"))); // NOI18N
        btnAddMainList.setText("Add");
        btnAddMainList.setName("mainlist"); // NOI18N

        btnRemoveMainList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus_icon_14px.png"))); // NOI18N
        btnRemoveMainList.setText("Remove");
        btnRemoveMainList.setName("mainlist"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("List Of Colleges");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddMainList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveMainList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMainList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveMainList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnPrograms.setBackground(new java.awt.Color(6, 136, 136));
        btnPrograms.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPrograms.setForeground(new java.awt.Color(255, 255, 255));
        btnPrograms.setText("Programs");
        btnPrograms.setBorder(null);
        btnPrograms.setBorderPainted(false);
        btnPrograms.setContentAreaFilled(false);
        btnPrograms.setMaximumSize(new java.awt.Dimension(217, 50));
        btnPrograms.setMinimumSize(new java.awt.Dimension(217, 50));
        btnPrograms.setOpaque(true);
        btnPrograms.setPreferredSize(new java.awt.Dimension(217, 50));

        btnAdministration.setBackground(new java.awt.Color(5, 119, 119));
        btnAdministration.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAdministration.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministration.setText("Administration");
        btnAdministration.setBorder(null);
        btnAdministration.setBorderPainted(false);
        btnAdministration.setContentAreaFilled(false);
        btnAdministration.setMaximumSize(new java.awt.Dimension(217, 50));
        btnAdministration.setMinimumSize(new java.awt.Dimension(217, 50));
        btnAdministration.setOpaque(true);
        btnAdministration.setPreferredSize(new java.awt.Dimension(217, 50));

        btnCouncils.setBackground(new java.awt.Color(5, 119, 119));
        btnCouncils.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCouncils.setForeground(new java.awt.Color(255, 255, 255));
        btnCouncils.setText("Councils");
        btnCouncils.setBorder(null);
        btnCouncils.setBorderPainted(false);
        btnCouncils.setContentAreaFilled(false);
        btnCouncils.setMaximumSize(new java.awt.Dimension(216, 50));
        btnCouncils.setMinimumSize(new java.awt.Dimension(216, 50));
        btnCouncils.setOpaque(true);
        btnCouncils.setPreferredSize(new java.awt.Dimension(216, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnPrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnCouncils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCouncils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(listSubMain);

        btnRemoveSubList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus_icon_14px.png"))); // NOI18N
        btnRemoveSubList.setText("Remove");
        btnRemoveSubList.setName("sublist"); // NOI18N

        btnAddSubList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus_icon_14px.png"))); // NOI18N
        btnAddSubList.setText("Add");
        btnAddSubList.setName("sublist"); // NOI18N

        lblEnterpriseTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEnterpriseTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnterpriseTitle.setText("Manage your enterprise here.");
        lblEnterpriseTitle.setVisible(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddSubList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveSubList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblEnterpriseTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterpriseTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSubList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveSubList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMainList;
    private javax.swing.JButton btnAddSubList;
    private javax.swing.JButton btnAdministration;
    private javax.swing.JButton btnCouncils;
    private javax.swing.JButton btnPrograms;
    private javax.swing.JButton btnRemoveMainList;
    private javax.swing.JButton btnRemoveSubList;
    private javax.swing.JLabel lblEnterpriseTitle;
    private javax.swing.JList<String> listMain;
    private javax.swing.JList<String> listSubMain;
    // End of variables declaration//GEN-END:variables

}
