package edu.neu.universityeventmanagementsystem.business.ui.shared.view;

import edu.neu.universityeventmanagementsystem.business.entity.EventsEntity;
import edu.neu.universityeventmanagementsystem.business.util.ConstantValues;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.util.Objects;

/**
 * EventRequestView class
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since Apr 25, 2018
 */
@Component
@Lazy
@Scope(value = "prototype")
public class EventRequestView extends javax.swing.JPanel {

    public static final int ADMIN_ROLE = 0;
    public static final int USER_ROLE = 1;

    private EventsEntity event;

    /**
     * Creates new form EventRequestView
     */
    public EventRequestView() {
        this(null, 1);
    }

    public EventRequestView(EventsEntity event, int role) {
        if (event == null) return;
        initComponents();

        if (role == ADMIN_ROLE) {
            btnDeleteEvent.setVisible(false);
            btnCancelEvent.setVisible(false);
            btnEditEvent.setVisible(false);
            return;
        }

        btnApproveEvent.setVisible(false);
        btnRejectEvent.setVisible(false);

        if (Objects.equals(event.getEventStatusByStatus().getStatusMessage(), ConstantValues.EventStatus.APPROVED)) {
            btnDeleteEvent.setEnabled(false);
            btnEditEvent.setVisible(false);
        }

        if (Objects.equals(event.getEventStatusByStatus().getStatusMessage(), ConstantValues.EventStatus.CANCELLED)) {
            btnCancelEvent.setText("Cancelled");
            btnCancelEvent.setEnabled(false);
            btnEditEvent.setVisible(false);
        }
    }

    public JButton getBtnCancelEvent() {
        return btnCancelEvent;
    }

    public JButton getBtnDeleteEvent() {
        return btnDeleteEvent;
    }

    public JButton getBtnEditEvent() {
        return btnEditEvent;
    }

    public JButton getBtnApproveEvent() {
        return btnApproveEvent;
    }

    public JButton getBtnRejectEvent() {
        return btnRejectEvent;
    }

    public void setEventView(java.awt.Component view) {
        eventPanel.removeAll();
        eventPanel.add(view);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        eventPanel = new javax.swing.JPanel();
        btnCancelEvent = new javax.swing.JButton();
        btnDeleteEvent = new javax.swing.JButton();
        btnEditEvent = new javax.swing.JButton();
        btnApproveEvent = new javax.swing.JButton();
        btnRejectEvent = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1092, 100));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 100));

        eventPanel.setBackground(new java.awt.Color(255, 255, 255));
        eventPanel.setPreferredSize(new java.awt.Dimension(480, 100));

        btnCancelEvent.setBackground(new java.awt.Color(204, 204, 0));
        btnCancelEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelEvent.setText("Cancel Event");
        btnCancelEvent.setContentAreaFilled(false);
        btnCancelEvent.setFocusPainted(false);
        btnCancelEvent.setOpaque(true);

        btnDeleteEvent.setBackground(new java.awt.Color(255, 0, 51));
        btnDeleteEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEvent.setText("Delete Event");
        btnDeleteEvent.setContentAreaFilled(false);
        btnDeleteEvent.setFocusPainted(false);
        btnDeleteEvent.setOpaque(true);

        btnEditEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_icon_48px.png"))); // NOI18N
        btnEditEvent.setContentAreaFilled(false);
        btnEditEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditEvent.setFocusPainted(false);

        btnApproveEvent.setBackground(new java.awt.Color(0, 204, 204));
        btnApproveEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnApproveEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnApproveEvent.setText("Approve Event");
        btnApproveEvent.setContentAreaFilled(false);
        btnApproveEvent.setFocusPainted(false);
        btnApproveEvent.setOpaque(true);

        btnRejectEvent.setBackground(new java.awt.Color(255, 0, 51));
        btnRejectEvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRejectEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnRejectEvent.setText("Reject Event");
        btnRejectEvent.setContentAreaFilled(false);
        btnRejectEvent.setFocusPainted(false);
        btnRejectEvent.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(eventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApproveEvent, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnRejectEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnApproveEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRejectEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEditEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveEvent;
    private javax.swing.JButton btnCancelEvent;
    private javax.swing.JButton btnDeleteEvent;
    private javax.swing.JButton btnEditEvent;
    private javax.swing.JButton btnRejectEvent;
    private javax.swing.JPanel eventPanel;
    // End of variables declaration//GEN-END:variables

}
