package edu.neu.universityeventmanagementsystem.business.ui.shared.view;

import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

/**
 * EventView class
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since Apr 21, 2018
 */
@Component
@Lazy
@Scope(value = "prototype")
public class EventView extends javax.swing.JPanel {

    public static final String EVENT_STATUS_REGISTERED = "Registered";
    public static final String EVENT_STATUS_REGISTER_NOW = "Register Now";
    public static final String EVENT_STATUS_OVER = "Over";
    public static final String EVENT_STATUS_PARTICIPATED = "Participated";
    public static final String EVENT_STATUS_HOST = "Hosted by you";

    /**
     * Creates new form EventEntityView
     */
    public EventView() {
        initComponents();
    }

    /**
     * Creates an event view with specified name and status
     *
     * @param name   Event name
     * @param status Event registration status
     * @param date Date of the event
     * @param location Location of the event
     */
    public EventView(String name, String status, Date date, String location) {
        if (!Objects.equals(status, EVENT_STATUS_OVER) ||
                !Objects.equals(status, EVENT_STATUS_REGISTER_NOW) ||
                !Objects.equals(status, EVENT_STATUS_REGISTERED) ||
                !Objects.equals(status, EVENT_STATUS_PARTICIPATED) ||
                !Objects.equals(status, EVENT_STATUS_HOST))
            status = "Unknown Status";

        initComponents();
        setEventName(name);
        setEventStatus(status);
        setEventDate(date);
        setEventLocation(location);
        setInvitedBy(" ");
    }

    /**
     * Creates an event view with specified name and status
     *
     * @param name   Event name
     * @param status Event registration status
     * @param date Date of the event
     * @param location Location of the event
     * @param invitedBy The person who invited the user
     */
    public EventView(String name, String status, Date date, String location, String invitedBy) {
        if (!Objects.equals(status, EVENT_STATUS_OVER) ||
                !Objects.equals(status, EVENT_STATUS_REGISTER_NOW) ||
                !Objects.equals(status, EVENT_STATUS_REGISTERED) ||
                !Objects.equals(status, EVENT_STATUS_PARTICIPATED) ||
                !Objects.equals(status, EVENT_STATUS_HOST))
            status = "Unknown Status";

        initComponents();
        setEventName(name);
        setEventStatus(status);
        setEventDate(date);
        setEventLocation(location);
        setInvitedBy(invitedBy);
    }

    public void setEventStatus(String status) {
        lblEventStatus.setText(status);
    }

    public void setEventName(String name) {
        lblEventName.setText(name);
    }

    public void setEventDate(Date date) {
        DateFormat df;
        try {
            if (date.after((new SimpleDateFormat("dd-MM-yyyy")).parse("01-01-2018")))
                df = new SimpleDateFormat("MMM, dd");
            else
                df = new SimpleDateFormat("MMM, dd yyyy");
        } catch (ParseException e) {
            df = new SimpleDateFormat("MMM, dd yyyy");
        }

        lblDate.setText(df.format(date));
    }

    public void setEventLocation(String location) {
        lblLocation.setText(location);
    }

    public void setInvitedBy(String invitedBy) {
        lblInvitedBy.setText(invitedBy);
    }
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        lblEventName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblEventStatus = new javax.swing.JLabel();
        lblInvitedBy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 0, 0));
        lblDate.setText("Apr, 21");

        lblEventName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventName.setText("The event name appears here. It will be truncated when it reaches....");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(0, 153, 153));
        lblLocation.setText("Location");

        lblEventStatus.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblEventStatus.setForeground(new java.awt.Color(0, 102, 204));
        lblEventStatus.setText("Event Status");

        lblInvitedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInvitedBy.setForeground(new java.awt.Color(0, 153, 153));
        lblInvitedBy.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLocation))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEventName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInvitedBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEventStatus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEventName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventStatus)
                    .addComponent(lblInvitedBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblEventStatus;
    private javax.swing.JLabel lblInvitedBy;
    private javax.swing.JLabel lblLocation;
    // End of variables declaration//GEN-END:variables

}
