package edu.neu.universityeventmanagementsystem.business.ui.shared.view;

import edu.neu.universityeventmanagementsystem.business.entity.EventsEntity;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

/**
 * EventView class
 *
 * @author Raghavan Renganathan <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since Apr 21, 2018
 */
@Component
@Lazy
@Scope(value = "prototype")
public class EventView extends javax.swing.JPanel {

    private EventsEntity event;

    public static final String EVENT_STATUS_REGISTERED = "Registered";
    public static final String EVENT_STATUS_REGISTER_NOW = "Register Now";
    public static final String EVENT_STATUS_OVER = "Over";
    public static final String EVENT_STATUS_PARTICIPATED = "Participated";
    public static final String EVENT_STATUS_HOST = "Hosted by you";

    /**
     * Creates new form EventEntityView
     */
    public EventView() {
        initComponents();
    }

    /**
     * Creates an event view with specified name and status
     *
     * @param event EventEntity object for which the view is being created
     * @param status Event status with respect to the user
     */
    public EventView(EventsEntity event, String status) {
        initComponents();

        this.event = event;
        if (!Objects.equals(status, EVENT_STATUS_OVER) &&
                !Objects.equals(status, EVENT_STATUS_REGISTER_NOW) &&
                !Objects.equals(status, EVENT_STATUS_REGISTERED) &&
                !Objects.equals(status, EVENT_STATUS_PARTICIPATED) &&
                !Objects.equals(status, EVENT_STATUS_HOST))
            status = "Unknown Status";

        status = adjustStatusBasedOnDate(status);

        setEventName(event.getName());
        setEventStatus(status);
        setEventDate(event.getStartTime());
        setEventLocation(event.getVenue());
        setInvitedBy(String.format("%s, %s", event.getUsersByIdCreator().getLastName(),
                                             event.getUsersByIdCreator().getFirstName()));
    }

    private String adjustStatusBasedOnDate(String status) {
        if (event.getStartTime().before(new Date()))
            return EVENT_STATUS_OVER;
        return status;
    }

    public EventsEntity getEvent() {
        return event;
    }

    public void setEventStatus(String status) {
        lblEventStatus.setText(status);
    }

    public void setEventName(String name) {
        lblEventName.setText(name);
    }

    public void setEventDate(Date date) {
        DateFormat df;
        try {
            if (date.after((new SimpleDateFormat("dd-MM-yyyy")).parse("01-01-2018")))
                df = new SimpleDateFormat("MMM, dd");
            else
                df = new SimpleDateFormat("MMM, dd yyyy");
        } catch (ParseException e) {
            df = new SimpleDateFormat("MMM, dd yyyy");
        }

        lblDate.setText(df.format(date));
    }

    public JLabel getLblEventStatus() {
        return lblEventStatus;
    }

    public void setEventLocation(String location) {
        lblLocation.setText(location);
    }

    public void setInvitedBy(String invitedBy) {
        lblInvitedBy.setText(invitedBy);
    }
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        lblEventName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblEventStatus = new javax.swing.JLabel();
        lblInvitedBy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 100));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 0, 0));
        lblDate.setText("Apr, 21");

        lblEventName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventName.setText("The event name appears here. It will be truncated when it reaches....");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(0, 153, 153));
        lblLocation.setText("Location");

        lblEventStatus.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblEventStatus.setForeground(new java.awt.Color(0, 102, 204));
        lblEventStatus.setText("Event Status");
        lblEventStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblInvitedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInvitedBy.setForeground(new java.awt.Color(0, 153, 153));
        lblInvitedBy.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                        .addComponent(lblLocation))
                    .addComponent(lblEventName)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInvitedBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEventStatus)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEventName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventStatus)
                    .addComponent(lblInvitedBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblEventStatus;
    private javax.swing.JLabel lblInvitedBy;
    private javax.swing.JLabel lblLocation;
    // End of variables declaration//GEN-END:variables

}
