package edu.neu.universityeventmanagementsystem.business.ui.shared.view;

import edu.neu.universityeventmanagementsystem.business.entity.NotificationsEntity;
import edu.neu.universityeventmanagementsystem.business.util.DateFormatTools;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.util.Date;

/**
 * NotificationView class
 *
 * @author  Raghavan Renganathan <renganathan.raghavan@gmail.com> <renganathan.r@husky.neu.edu>
 * @version 1.0
 * @since   Apr 26, 2018
 */
@Component
@Scope(value = "prototype")
@Lazy
public class NotificationView extends javax.swing.JPanel {

    private NotificationsEntity notification;

    /** Creates new form NotificationView */
    public NotificationView() {
        this(null);
    }

    public NotificationView(NotificationsEntity notification) {
        this.notification = notification;
        initComponents();
        if (notification != null) {
            setTitle(notification.getMessage());
            setEventName(notification.getEventsByIdEvent().getName());
            setEventLocation(notification.getEventsByIdEvent().getVenue());
            setEventDate(notification.getEventsByIdEvent().getStartTime());
            setIsNew(notification.isReadFlag());
        }
    }

    public void setTitle(String title) {
        lblTitle.setText(title);
    }

    public void setEventLocation(String location) {
        lblEventLocation.setText(location);
    }

    public void setEventName(String name) {
        lblEventName.setText(name);
    }

    public void setEventDate(Date date) {
        lblEventDate.setText(DateFormatTools.formatDate(date));
    }

    public void setIsNew(boolean isRead) {
        lblNewIcon.setVisible(!isRead);
    }

    public JLabel getDeleteButton() {
        return lblClearNotification;
    }

    public NotificationsEntity getNotification() {
        return notification;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        lblNewIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        lblEventName = new javax.swing.JLabel();
        lblEventDate = new javax.swing.JLabel();
        lblEventLocation = new javax.swing.JLabel();
        lblClearNotification = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(276, 99));

        lblNewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_icon_25px.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitle.setText("Notification Title");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/events_icon.png"))); // NOI18N

        lblEventName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEventName.setText("Event name goes here.");

        lblEventDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEventDate.setForeground(new java.awt.Color(204, 0, 0));
        lblEventDate.setText("Apr, 21");

        lblEventLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEventLocation.setForeground(new java.awt.Color(0, 153, 153));
        lblEventLocation.setText("Location");

        lblClearNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove_icon_16px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblClearNotification))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEventName)
                                .addGap(0, 82, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEventDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEventLocation)))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addComponent(lblNewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClearNotification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEventName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEventDate)
                            .addComponent(lblEventLocation))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel lblClearNotification;
    javax.swing.JLabel lblEventDate;
    javax.swing.JLabel lblEventLocation;
    javax.swing.JLabel lblEventName;
    javax.swing.JLabel lblNewIcon;
    javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
